### ISSUE TITLE
Help_en: add chapter Preferences

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#25]

**Comment by krHERO** [comment]
i am not sure if i understand the issue right, since the description is only the title. 
if this issue wants to add a section how to customize the preference-file of edirom-online, i want to suggest to close this issue. @bwbohl  do you agree on that idea?
* not the correct place: in the user help, i do not expect a "tutorial" how to customize the software
* already some documentation provided
  * see [customize.md](https://github.com/Edirom/Edirom-Online/blob/develop/docs/customize.md) ([PR494](https://github.com/Edirom/Edirom-Online/pull/494) adds link to preference-file)
  * the [prefs](https://github.com/Edirom/Edirom-Online/tree/develop/add/data/prefs) directory contains besides the preferences file itself also a readme.md with some information
