### ISSUE TITLE
Help_en: add chapter searchView

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#26]

**Comment by krHERO** [comment]
i am not sure if i understand this issue correctly, since the description is only the title.

if this issue wants to add a description how the search works and looks like, i suggest to close this issue. do you agree on that, @bwbohl ? 

the help already has a chapter about the search view 
<img width="878" alt="Bildschirmfoto 2024-12-05 um 21 17 58" src="https://github.com/user-attachments/assets/129a5004-b7ef-4011-b86f-11c4bae290e8">

and referring to the [revisionDesc](https://github.com/Edirom/Edirom-Online/blob/4a5996475f043aa70b153a38101ee5fee9a454e5/add/help/help_en.xml#L44) of the help file it was added already some time ago.
`<change when="2013-08-08" who="#bwb">* added description of searchWindow; deactivated link to missing preferences section;</change>`
