### ISSUE TITLE
View HelpWindow: back links

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#27]
Navigating help with its internal links gives no option of going back to previous anchors.

A window history would be feasible.

**Comment by bwbohl** [comment]
any preferences?

**Comment by krHERO** [comment]
i want to close this issue for two reasons

- while working on #471 i did several sum ups,  merged text-duplicates, deleted deprecated text-parts etc, so the text itself is shorter already
- people are more used to scroll (even larger texts) nowadays. plus several back links could even perceived as disturbing these days instead of supportive regarding navigation
