### ISSUE TITLE
gotoMeasure in renderingView broken

### ISSUE THREAD

**Issue by kepper** [Edirom/Edirom-Online#277]
<img width="271" alt="grafik" src="https://user-images.githubusercontent.com/2078563/175763831-2acec2a7-4934-4e28-bb2a-2c2e0c44fd63.png">

<img width="350" alt="grafik" src="https://user-images.githubusercontent.com/2078563/175763857-2cd690c3-85ef-4729-ba84-93e4a809d502.png">

<img width="498" alt="grafik" src="https://user-images.githubusercontent.com/2078563/175763804-7dc32649-aade-4aa7-afa5-5b29e92c979a.png">

**Comment by bwbohl** [comment]
by default SourceView calls showMeasure in MeasureBasedView that's why the function is missing in VerovioView. We should come up with a general concept in which views the functionality should be available and to which result and if both VerovioView and MeasureBasedView are available for a source, which one to prefer.
