### ISSUE TITLE
integrate help web component

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#43]
the new english help has to be translated to german

**Comment by daniel-jettka** [comment]
Hi @bwbohl Which help is this about?
I had a look at Freischütz... mostly German, only headings English. 
In principle we could also think about a Edirom Help web component.

![image](https://github.com/Edirom/Edirom-Online/assets/18614293/6b2cbe4e-e6bc-4d57-abcf-e475464d1073)

**Comment by bwbohl** [comment]
there was a separate repo for edirom help at some point, should have a local dump here. And yes, making this a component could be a good idea!

**Comment by krHERO** [comment]
since this issue was originally about the german help, that needed to be added based on the translation of the english help, i want to close this issue. the translation to german based on the english help text was already done in june 2014 https://github.com/Edirom/Edirom-Online/blob/bbf893a4ce7892e19de7f4db111f6864f97cac7e/add/help/help_de.xml#L31
regarding help as a web component it seems more meaningful to have a text web component in general, so we do not want to have content as web components. when the work on this topic starts, a new issue will be created to capture every discussion and content at this place.
